apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: gcr.io/e-varejo/frontend:v1
          ports:
          - containerPort: 80
          lifecycle:
            preStop:
              exec:
                command: ["/usr/sbin/nginx","-s","quit"]
          env:
          - name: REACT_APP_API_HOST
            value: http://35.199.73.142/
---

apiVersion: v1
kind: Service
metadata:
  name: frontend-external
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
  - protocol: TCP
    name: http-front
    port: 80 #porta que vai ser exposta
    targetPort: 80 #porta no container    
